services:

  postgres:
    image: postgres:16
    container_name: library-postgres

    environment:
      POSTGRES_DB: librarydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    restart: unless-stopped

volumes:
  postgres_data:

  #Restart policy options:
  #no — Don't automatically restart
  #always — Always restart, even if you stopped it
  #unless-stopped — Restart unless explicitly stopped (most common)
  #on-failure — Restart only if container exits with non-zero code
  